---
R1:
  hostname: 192.168.81.153
  groups: 
    - cisco_routers

R2:
  hostname: 192.168.81.152
  groups: 
    - cisco_routers

R3:
  hostname: 192.168.81.151
  groups:
    - cisco_routers

R4: 
  hostname: 192.168.81.150
  groups:
    - cisco_routers

SW:
  hostname: 192.168.81.135
  groups:
    - cisco_switches

SW2:
  hostname: 192.168.81.145
  groups:
    - cisco_switches
